### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by MinhMPA** [Tomoaki-Ishiyama/mpi-rockstar#26]
Compilation now fails after the merge introducing `LIGHTCONE` features in `src/properties.c`

```
properties.c: In function ‘max_halo_radius’:
properties.c:5:9: error: ‘LIGHTCONE’ undeclared (first use in this function)
     if (LIGHTCONE)
         ^
properties.c:5:9: note: each undeclared identifier is reported only once for each function it appears in
properties.c:6:9: warning: implicit declaration of function ‘lightcone_set_scale’ [-Wimplicit-function-declaration]
         lightcone_set_scale(h->pos);
         ^
properties.c:7:25: error: ‘particle_thresh_dens’ undeclared (first use in this function)
     float thresh_dens = particle_thresh_dens[min_dens_index] * PARTICLE_MASS;
                         ^
properties.c:7:46: error: ‘min_dens_index’ undeclared (first use in this function)
     float thresh_dens = particle_thresh_dens[min_dens_index] * PARTICLE_MASS;
                                              ^
properties.c:7:64: error: ‘PARTICLE_MASS’ undeclared (first use in this function)
     float thresh_dens = particle_thresh_dens[min_dens_index] * PARTICLE_MASS;
                                                                ^
properties.c:9:5: warning: implicit declaration of function ‘cbrt’ [-Wimplicit-function-declaration]
     return (cbrt((3.0 / (4.0 * M_PI)) * m / thresh_dens) * 1e3);
     ^
properties.c:9:13: warning: incompatible implicit declaration of built-in function ‘cbrt’ [enabled by default]
     return (cbrt((3.0 / (4.0 * M_PI)) * m / thresh_dens) * 1e3);
             ^
properties.c:9:32: error: ‘M_PI’ undeclared (first use in this function)
     return (cbrt((3.0 / (4.0 * M_PI)) * m / thresh_dens) * 1e3);
                                ^
properties.c: At top level:
properties.c:14:39: warning: ‘struct HaloInfo’ declared inside parameter list [enabled by default]
                          const struct HaloInfo *haloinfo) {
                                       ^
properties.c:14:39: warning: its scope is only this definition or declaration, which is probably not what you want [enabled by default]
properties.c: In function ‘_populate_mass_bins’:
properties.c:19:30: error: ‘copies’ undeclared (first use in this function)
             dx = h->pos[j] - copies[cur_h->p_start + i].pos[j];
                              ^
properties.c:22:9: warning: implicit declaration of function ‘sqrt’ [-Wimplicit-function-declaration]
         bin = sqrt(ds) * r_scale;
         ^
properties.c:22:15: warning: incompatible implicit declaration of built-in function ‘sqrt’ [enabled by default]
         bin = sqrt(ds) * r_scale;
               ^
properties.c:30:35: error: dereferencing pointer to incomplete type
     first_child = child = haloinfo->extra_info[cur_h - haloinfo->halos].child;
                                   ^
properties.c:30:64: error: dereferencing pointer to incomplete type
     first_child = child = haloinfo->extra_info[cur_h - haloinfo->halos].child;
                                                                ^
properties.c:32:40: error: dereferencing pointer to incomplete type
         _populate_mass_bins(h, haloinfo->halos + child, bins, num_bins, r_scale,
                                        ^
properties.c:34:25: error: dereferencing pointer to incomplete type
         child = haloinfo->extra_info[child].next_cochild;
                         ^
properties.c:35:9: warning: implicit declaration of function ‘assert’ [-Wimplicit-function-declaration]
         assert(child != first_child);
         ^
properties.c: In function ‘_estimate_vmax’:
properties.c:44:17: error: ‘FORCE_RES’ undeclared (first use in this function)
         if (r < FORCE_RES)
                 ^
properties.c:52:23: error: ‘LIGHTCONE’ undeclared (first use in this function)
     float scale_now = LIGHTCONE ? scale_dx : SCALE_NOW;
                       ^
properties.c:52:35: error: ‘scale_dx’ undeclared (first use in this function)
     float scale_now = LIGHTCONE ? scale_dx : SCALE_NOW;
                                   ^
properties.c:52:46: error: ‘SCALE_NOW’ undeclared (first use in this function)
     float scale_now = LIGHTCONE ? scale_dx : SCALE_NOW;
                                              ^
properties.c:54:12: warning: incompatible implicit declaration of built-in function ‘sqrt’ [enabled by default]
     return sqrt(Gc * vmax * PARTICLE_MASS / scale_now);
            ^
properties.c:54:17: error: ‘Gc’ undeclared (first use in this function)
     return sqrt(Gc * vmax * PARTICLE_MASS / scale_now);
                 ^
properties.c:54:29: error: ‘PARTICLE_MASS’ undeclared (first use in this function)
     return sqrt(Gc * vmax * PARTICLE_MASS / scale_now);
                             ^
properties.c: At top level:
properties.c:57:49: warning: ‘struct HaloInfo’ declared inside parameter list [enabled by default]
 void estimate_vmax(struct halo *h, const struct HaloInfo *haloinfo) {
                                                 ^
properties.c: In function ‘estimate_vmax’:
properties.c:63:23: error: ‘LIGHTCONE’ undeclared (first use in this function)
     float scale_now = LIGHTCONE ? scale_dx : SCALE_NOW;
                       ^
properties.c:63:35: error: ‘scale_dx’ undeclared (first use in this function)
     float scale_now = LIGHTCONE ? scale_dx : SCALE_NOW;
                                   ^
properties.c:63:46: error: ‘SCALE_NOW’ undeclared (first use in this function)
     float scale_now = LIGHTCONE ? scale_dx : SCALE_NOW;
                                              ^
properties.c:65:5: warning: passing argument 7 of ‘_populate_mass_bins’ from incompatible pointer type [enabled by default]
     _populate_mass_bins(h, h, bins, VMAX_BINS, r_scale, 0, haloinfo);
     ^
properties.c:12:6: note: expected ‘const struct HaloInfo *’ but argument is of type ‘const struct HaloInfo *’
 void _populate_mass_bins(struct halo *h, struct halo *cur_h, int64_t *bins,
      ^
properties.c:67:17: warning: incompatible implicit declaration of built-in function ‘sqrt’ [enabled by default]
     h->vmax_r = sqrt(scale_now) * _estimate_vmax(bins, VMAX_BINS, r_scale) *
                 ^
properties.c:68:17: error: ‘dynamical_time’ undeclared (first use in this function)
                 dynamical_time;
                 ^
properties.c: At top level:
properties.c:71:57: warning: ‘struct HaloInfo’ declared inside parameter list [enabled by default]
 void calc_basic_halo_props(struct halo *h, const struct HaloInfo *haloinfo) {
                                                         ^
properties.c: In function ‘calc_basic_halo_props’:
properties.c:78:23: error: ‘copies’ undeclared (first use in this function)
             pos[k] += copies[h->p_start + j].pos[k];
                       ^
properties.c:118:18: warning: incompatible implicit declaration of built-in function ‘cbrt’ [enabled by default]
     h->r       = cbrt(h->num_p / ((4.0 * M_PI / 3.0) * particle_rvir_dens));
                  ^
properties.c:118:42: error: ‘M_PI’ undeclared (first use in this function)
     h->r       = cbrt(h->num_p / ((4.0 * M_PI / 3.0) * particle_rvir_dens));
                                          ^
properties.c:118:56: error: ‘particle_rvir_dens’ undeclared (first use in this function)
     h->r       = cbrt(h->num_p / ((4.0 * M_PI / 3.0) * particle_rvir_dens));
                                                        ^
properties.c:121:5: warning: passing argument 2 of ‘estimate_vmax’ from incompatible pointer type [enabled by default]
     estimate_vmax(h, haloinfo);
     ^
properties.c:57:6: note: expected ‘const struct HaloInfo *’ but argument is of type ‘const struct HaloInfo *’
 void estimate_vmax(struct halo *h, const struct HaloInfo *haloinfo) {
      ^
properties.c:124:15: warning: incompatible implicit declaration of built-in function ‘sqrt’ [enabled by default]
     h->vrms = sqrt(h->vrms);
               ^
properties.c: At top level:
properties.c:140:45: warning: ‘struct HaloInfo’ declared inside parameter list [enabled by default]
                                const struct HaloInfo *haloinfo) {
                                             ^
properties.c: In function ‘_calc_num_child_particles’:
properties.c:146:35: error: dereferencing pointer to incomplete type
     first_child = child = haloinfo->extra_info[h - haloinfo->halos].child;
                                   ^
properties.c:146:60: error: dereferencing pointer to incomplete type
     first_child = child = haloinfo->extra_info[h - haloinfo->halos].child;
                                                            ^
properties.c:148:43: error: dereferencing pointer to incomplete type
         _calc_num_child_particles(haloinfo->halos + child, haloinfo);
                                           ^
properties.c:149:43: error: dereferencing pointer to incomplete type
         h->num_child_particles += haloinfo->halos[child].num_child_particles;
                                           ^
properties.c:150:25: error: dereferencing pointer to incomplete type
         child = haloinfo->extra_info[child].next_cochild;
                         ^
properties.c: At top level:
properties.c:156:44: warning: ‘struct HaloInfo’ declared inside parameter list [enabled by default]
                               const struct HaloInfo *haloinfo) {
                                            ^
properties.c: In function ‘calc_num_child_particles’:
properties.c:158:35: error: dereferencing pointer to incomplete type
     for (i = h_start; i < haloinfo->num_halos; i++)
                                   ^
properties.c:159:17: error: dereferencing pointer to incomplete type
         haloinfo->halos[i].num_child_particles = 0;
                 ^
properties.c:160:35: error: dereferencing pointer to incomplete type
     for (i = h_start; i < haloinfo->num_halos; i++)
                                   ^
properties.c:161:22: error: dereferencing pointer to incomplete type
         if (!haloinfo->halos[i].num_child_particles)
                      ^
properties.c:162:47: error: dereferencing pointer to incomplete type
             _calc_num_child_particles(haloinfo->halos + i, haloinfo);
                                               ^
properties.c:162:13: warning: passing argument 2 of ‘_calc_num_child_particles’ from incompatible pointer type [enabled by default]
             _calc_num_child_particles(haloinfo->halos + i, haloinfo);
             ^
properties.c:139:6: note: expected ‘const struct HaloInfo *’ but argument is of type ‘const struct HaloInfo *’
 void _calc_num_child_particles(struct halo           *h,
      ^
properties.c: In function ‘calculate_corevel’:
properties.c:171:27: error: ‘particle_rvir_dens’ undeclared (first use in this function)
     double  rvir_thresh = particle_rvir_dens * (4.0 * M_PI / 3.0);
                           ^
properties.c:171:55: error: ‘M_PI’ undeclared (first use in this function)
     double  rvir_thresh = particle_rvir_dens * (4.0 * M_PI / 3.0);
                                                       ^
properties.c: In function ‘calc_shape’:
properties.c:217:32: error: ‘SHAPE_ITERATIONS’ undeclared (first use in this function)
     int64_t i, j, k, l, iter = SHAPE_ITERATIONS, analyze_p = 0, a, b, c;
                                ^
properties.c:218:48: error: ‘FORCE_RES’ undeclared (first use in this function)
     float   b_to_a, c_to_a, min_r            = FORCE_RES * FORCE_RES;
                                                ^
properties.c:221:5: warning: implicit declaration of function ‘memset’ [-Wimplicit-function-declaration]
     memset(h->A, 0, sizeof(float) * 3);
     ^
properties.c:221:5: warning: incompatible implicit declaration of built-in function ‘memset’ [enabled by default]
properties.c:227:23: error: ‘po’ undeclared (first use in this function)
         if (bound && (po[j].pe < po[j].ke))
                       ^
properties.c:259:26: error: ‘WEIGHTED_SHAPES’ undeclared (first use in this function)
             double tw = (WEIGHTED_SHAPES) ? 1.0 / r : 1.0;
                          ^
properties.c:280:2: warning: implicit declaration of function ‘memcpy’ [-Wimplicit-function-declaration]
  memcpy( mass_t2, mass_t, sizeof(double)*9);
  ^
properties.c:280:2: warning: incompatible implicit declaration of built-in function ‘memcpy’ [enabled by default]
properties.c:283:9: warning: implicit declaration of function ‘jacobi_decompose’ [-Wimplicit-function-declaration]
         jacobi_decompose(mass_t, eig, orth);
         ^
properties.c:302:18: warning: incompatible implicit declaration of built-in function ‘sqrt’ [enabled by default]
         b_to_a = sqrt(eig[b] / eig[a]);
                  ^
properties.c:304:9: warning: implicit declaration of function ‘fabs’ [-Wimplicit-function-declaration]
         if ((fabs(b_to_a - h->b_to_a) < 0.01 * h->b_to_a) &&
         ^
properties.c:304:14: warning: incompatible implicit declaration of built-in function ‘fabs’ [enabled by default]
         if ((fabs(b_to_a - h->b_to_a) < 0.01 * h->b_to_a) &&
              ^
properties.c: In function ‘estimate_total_energy’:
properties.c:332:13: error: ‘po’ undeclared (first use in this function)
         if (po[i].pe > po[i].ke) {
             ^
properties.c:334:17: warning: incompatible implicit declaration of built-in function ‘sqrt’ [enabled by default]
             r = sqrt(po[i].r2);
                 ^
properties.c:335:21: error: ‘FORCE_RES’ undeclared (first use in this function)
             if (r < FORCE_RES)
                     ^
properties.c:337:26: error: ‘PARTICLE_MASS’ undeclared (first use in this function)
             total_phi += PARTICLE_MASS * i / r + phi;
                          ^
properties.c:346:23: error: ‘LIGHTCONE’ undeclared (first use in this function)
     float scale_now = LIGHTCONE ? scale_dx : SCALE_NOW;
                       ^
properties.c:346:35: error: ‘scale_dx’ undeclared (first use in this function)
     float scale_now = LIGHTCONE ? scale_dx : SCALE_NOW;
                                   ^
properties.c:346:46: error: ‘SCALE_NOW’ undeclared (first use in this function)
     float scale_now = LIGHTCONE ? scale_dx : SCALE_NOW;
                                              ^
properties.c:348:48: error: ‘Gc’ undeclared (first use in this function)
     return ((ke - total_phi) * PARTICLE_MASS * Gc / scale_now);
                                                ^
properties.c: In function ‘_calc_pseudo_evolution_masses’:
properties.c:363:23: error: ‘po’ undeclared (first use in this function)
         if (bound && (po[j].pe < po[j].ke))
                       ^
properties.c:366:13: warning: incompatible implicit declaration of built-in function ‘sqrt’ [enabled by default]
         r = sqrt(po[j].r2);
             ^
properties.c:379:33: error: ‘PARTICLE_MASS’ undeclared (first use in this function)
     h->m_pe_d = num_part_pe_d * PARTICLE_MASS;
                                 ^
properties.c:380:5: warning: implicit declaration of function ‘pow’ [-Wimplicit-function-declaration]
     h->m_pe_b = PARTICLE_MASS * pow(max_pe_b, 2.0 / 3.0) /
     ^
properties.c:380:33: warning: incompatible implicit declaration of built-in function ‘pow’ [enabled by default]
     h->m_pe_b = PARTICLE_MASS * pow(max_pe_b, 2.0 / 3.0) /
                                 ^
properties.c:381:17: warning: incompatible implicit declaration of built-in function ‘cbrt’ [enabled by default]
                 cbrt(4.0 * M_PI * particle_rvir_dens_z0 / 3.0);
                 ^
properties.c:381:28: error: ‘M_PI’ undeclared (first use in this function)
                 cbrt(4.0 * M_PI * particle_rvir_dens_z0 / 3.0);
                            ^
properties.c:381:35: error: ‘particle_rvir_dens_z0’ undeclared (first use in this function)
                 cbrt(4.0 * M_PI * particle_rvir_dens_z0 / 3.0);
                                   ^
properties.c: In function ‘_calc_additional_halo_props’:
properties.c:389:23: error: ‘LIGHTCONE’ undeclared (first use in this function)
     float scale_now = LIGHTCONE ? scale_dx : SCALE_NOW;
                       ^
properties.c:389:35: error: ‘scale_dx’ undeclared (first use in this function)
     float scale_now = LIGHTCONE ? scale_dx : SCALE_NOW;
                                   ^
properties.c:389:46: error: ‘SCALE_NOW’ undeclared (first use in this function)
     float scale_now = LIGHTCONE ? scale_dx : SCALE_NOW;
                                              ^
properties.c:391:26: error: ‘particle_thresh_dens’ undeclared (first use in this function)
     double dens_thresh = particle_thresh_dens[0] * (4.0 * M_PI / 3.0);
                          ^
properties.c:391:59: error: ‘M_PI’ undeclared (first use in this function)
     double dens_thresh = particle_thresh_dens[0] * (4.0 * M_PI / 3.0);
                                                           ^
properties.c:396:26: error: ‘particle_rvir_dens’ undeclared (first use in this function)
     double rvir_thresh = particle_rvir_dens * (4.0 * M_PI / 3.0);
                          ^
properties.c:397:26: error: ‘PARTICLE_MASS’ undeclared (first use in this function)
     double vmax_conv   = PARTICLE_MASS / scale_now;
                          ^
properties.c:403:23: error: ‘po’ undeclared (first use in this function)
         if (bound && (po[j].pe < po[j].ke))
                       ^
properties.c:406:13: warning: incompatible implicit declaration of built-in function ‘sqrt’ [enabled by default]
         r = sqrt(po[j].r2);
             ^
properties.c:407:17: error: ‘FORCE_RES’ undeclared (first use in this function)
         if (r < FORCE_RES)
                 ^
properties.c:457:23: error: ‘BOUND_PROPS’ undeclared (first use in this function)
     if ((!bound) == (!BOUND_PROPS)) { // Works even if BOUND_PROPS > 1
                       ^
properties.c:469:30: warning: incompatible implicit declaration of built-in function ‘sqrt’ [enabled by default]
         h->Xoff            = sqrt(h->Xoff) * 1e3;
                              ^
properties.c:472:30: error: ‘VMAX_CONST’ undeclared (first use in this function)
         h->vmax            = VMAX_CONST * sqrt(vmax * vmax_conv);
                              ^
properties.c:476:13: warning: incompatible implicit declaration of built-in function ‘cbrt’ [enabled by default]
             cbrt((3.0 / (4.0 * M_PI)) * np_alt[2] / particle_thresh_dens[3]) *
             ^
properties.c:481:9: warning: incompatible implicit declaration of built-in function ‘memcpy’ [enabled by default]
         memcpy(h->A2, h->A, sizeof(float) * 3);
         ^
properties.c:495:9: warning: implicit declaration of function ‘calc_scale_radius’ [-Wimplicit-function-declaration]
         calc_scale_radius(h, m, h->r, h->vmax, h->rvmax, scale_now, po,
         ^
properties.c:503:34: warning: incompatible implicit declaration of built-in function ‘fabs’ [enabled by default]
             (m > 0) ? (Jh * sqrt(fabs(h->energy)) / (Gc * pow(m, 2.5))) : 0;
                                  ^
properties.c:503:54: error: ‘Gc’ undeclared (first use in this function)
             (m > 0) ? (Jh * sqrt(fabs(h->energy)) / (Gc * pow(m, 2.5))) : 0;
                                                      ^
properties.c:503:59: warning: incompatible implicit declaration of built-in function ‘pow’ [enabled by default]
             (m > 0) ? (Jh * sqrt(fabs(h->energy)) / (Gc * pow(m, 2.5))) : 0;
                                                           ^
properties.c: At top level:
properties.c:514:46: warning: ‘struct HaloInfo’ declared inside parameter list [enabled by default]
                                 const struct HaloInfo *haloinfo) {
                                              ^
properties.c: In function ‘calc_additional_halo_props’:
properties.c:518:9: error: ‘LIGHTCONE’ undeclared (first use in this function)
     if (LIGHTCONE)
         ^
properties.c:521:35: error: ‘scale_dx’ undeclared (first use in this function)
     float scale_now = LIGHTCONE ? scale_dx : SCALE_NOW;
                                   ^
properties.c:521:46: error: ‘SCALE_NOW’ undeclared (first use in this function)
     float scale_now = LIGHTCONE ? scale_dx : SCALE_NOW;
                                              ^
properties.c:523:19: error: ‘particle_thresh_dens’ undeclared (first use in this function)
     dens_thresh = particle_thresh_dens[0] * (4.0 * M_PI / 3.0);
                   ^
properties.c:523:52: error: ‘M_PI’ undeclared (first use in this function)
     dens_thresh = particle_thresh_dens[0] * (4.0 * M_PI / 3.0);
                                                    ^
properties.c:526:5: warning: implicit declaration of function ‘calc_particle_radii’ [-Wimplicit-function-declaration]
     total_p = calc_particle_radii(h, h, h->pos, 0, 0, 0, haloinfo);
     ^
properties.c:527:9: error: ‘BOUND_OUT_TO_HALO_EDGE’ undeclared (first use in this function)
     if (BOUND_OUT_TO_HALO_EDGE) {
         ^
properties.c:528:9: warning: implicit declaration of function ‘qsort’ [-Wimplicit-function-declaration]
         qsort(po, total_p, sizeof(struct potential), dist_compare);
         ^
properties.c:528:15: error: ‘po’ undeclared (first use in this function)
         qsort(po, total_p, sizeof(struct potential), dist_compare);
               ^
properties.c:528:54: error: ‘dist_compare’ undeclared (first use in this function)
         qsort(po, total_p, sizeof(struct potential), dist_compare);
                                                      ^
properties.c:547:17: error: dereferencing pointer to incomplete type
     if (haloinfo->extra_info[h - haloinfo->halos].sub_of > -1)
                 ^
properties.c:547:42: error: dereferencing pointer to incomplete type
     if (haloinfo->extra_info[h - haloinfo->halos].sub_of > -1)
                                          ^
properties.c:554:33: error: ‘NULL’ undeclared (first use in this function)
     if (analyze_halo_generic != NULL)
                                 ^
properties.c: In function ‘max_halo_radius’:
properties.c:10:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
properties.c: In function ‘_estimate_vmax’:
properties.c:55:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
properties.c: In function ‘estimate_total_energy’:
properties.c:349:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
```

**Comment by Tomoaki-Ishiyama** [comment]
@MinhMPA Thank you so much for reporting this issue. But I could not reproduce it. Could you tell me more details about what you did?

**Comment by MinhMPA** [comment]
My apologies! It turns out to be an issue from my own local paths. I'll close the issue for now.
